language: objective-c
osx_image: xcode7.1
env:
  matrix:
    - DESTINATION="OS=9.1,name=iPad 2"
before_install:
  - gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild -project Example/DynamicButtonExample.xcodeproj -scheme DynamicButtonTests -sdk iphonesimulator -destination "$DESTINATION" -configuration Release test | xcpretty -c
  - xcodebuild -project Example/DynamicButtonExample.xcodeproj -scheme DynamicButtonExampleUITests -sdk iphonesimulator -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
